# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyize_url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='url_count',
            field=models.IntegerField(default=0),
        ),
    ]
